/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaloveu.app;

import static javaloveu.hfdp.DesignPattern.runHDFP;

public class App {
    public static void main(String[] args) {
        runHDFP();
    }
}
